jwt:
  secret: '[gnaofgna25+2-660]^%%^$&!#%$^!agofgGVA9+A9G+**5A[0-99]aa*[a-Z]4[Z-A]#$^%&^*&(*&&)&(^*&%$AGREHTGMH<J<'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    password: here should be your own password
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

